update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,32 +22,43 @@ jobs:
 
       - name: Get previous run artifact
         run: |
-            ARTIFACT_ID=$(curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=allure-results" \
-            | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") && \
-            curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip \
-            -o artifacts.zip && \
-            REPORT_ID=$(curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=github-pages" \
-            | python -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);") && \
-            curl -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$REPORT_ID/zip \
-            -o pages.zip
+          ARTIFACT_ID=$(curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=allure-results" \
+          | python -c "import sys, json; artifacts = json.load(sys.stdin)['artifacts']; print(artifacts[0]['id'] if artifacts else 'No artifacts found');") && \
+          echo "Artifact ID: $ARTIFACT_ID" && \
+          if [ "$ARTIFACT_ID" = "No artifacts found" ]; then exit 1; fi && \
+          curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip \
+          -o artifacts.zip
 
-      - run: mkdir allure-results && unzip artifacts.zip -d allure-results ||true
-      - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history ||true
-      - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results ||true
+      - name: Check if artifacts.zip is valid
+        run: unzip -t artifacts.zip || echo "Artifacts zip is invalid"
+
+      - run: mkdir allure-results && unzip artifacts.zip -d allure-results || true
+
+      - name: Get previous pages artifact
+        run: |
+          REPORT_ID=$(curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts?name=github-pages" \
+          | python -c "import sys, json; artifacts = json.load(sys.stdin)['artifacts']; print(artifacts[0]['id'] if artifacts else 'No artifacts found');") && \
+          echo "Report ID: $REPORT_ID" && \
+          if [ "$REPORT_ID" = "No artifacts found" ]; then exit 1; fi && \
+          curl -L \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$REPORT_ID/zip \
+          -o pages.zip
+
+      - run: mkdir old_pages pages_history && unzip pages.zip -d old_pages && tar -xvf old_pages/artifact.tar -C pages_history || true
+      - run: cp pages_history/history/* allure-results && cp -r pages_history/history allure-results || true
 
       - name: Check if allure-results is not empty
         run: test -n "$(ls -A allure-results)" || echo "No Allure results found"
@@ -57,8 +68,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: allure-results
-          path:
-            allure-results
+          path: allure-results
           retention-days: 10
 
 
@@ -84,9 +94,6 @@ jobs:
       - name: Install requirements
         run: pip install -r requirements.txt
 
-      - name: Download all workflow run artifacts
-        uses: actions/download-artifact@v4
-
       - name: Run tests
         run: pytest --alluredir="allure-results"
         env:
@@ -103,8 +110,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: allure-results
-          path:
-            allure-results
+          path: allure-results
           retention-days: 10
 
 
@@ -132,8 +138,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: _site
-          path:
-            _site
+          path: _site
           retention-days: 10
 
 
@@ -146,12 +151,11 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: _site
-          path:
-            _site
+          path: _site
 
       - name: Upload Pages artifact
         uses: actions/upload-pages-artifact@v2
 
-      - name: Deploy to gitHub Pages
+      - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v1.2.9
